
server:
  port: 8001

spring:
  application:
    name: kotlin-web
  dubbo:
    application:
      name: kotlin-web
    registry:
      address: zookeeper://127.0.0.1:2181
      check: false
    scan: com.github.hykes.demo.front
    module: consumer
    protocol:
      name: dubbo
      port: 20880

